In [6]:
import pandas as pd
import sqlite3
customers = pd.read_csv("../data/raw/01_fund_master.csv")
conn = sqlite3.connect("../data/db/mutualfund.db")

In [8]:
customers.to_sql(
    "customers",
    conn,
    if_exists="replace",
    index=False
)

40

In [9]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

pd.read_sql(query,conn)

           name
0    navhistory
1       aumbyfh
2     sipinflow
3     catinflow
4    foliocount
5    schemeperf
6  transactions
7     pholdings
8    benchmarks
9     customers

In [7]:
query = """
SELECT COUNT(*)
FROM customers;
"""

pd.read_sql(query,conn)

   COUNT(*)
0        40

In [3]:
query = """
SELECT COUNT(*)
FROM navhistory;
"""

pd.read_sql(query,conn)

   COUNT(*)
0     46000

In [9]:
query = """
SELECT COUNT(*)
FROM aumbyfh;
"""

pd.read_sql(query,conn)

   COUNT(*)
0        90

In [10]:
query = """
SELECT COUNT(*)
FROM sipinflow;
"""

pd.read_sql(query,conn)

   COUNT(*)
0        48

In [11]:
query = """
SELECT COUNT(*)
FROM catinflow;
"""

pd.read_sql(query,conn)

   COUNT(*)
0       144

In [12]:
query = """
SELECT COUNT(*)
FROM foliocount;
"""

pd.read_sql(query,conn)

   COUNT(*)
0        21

In [13]:
query = """
SELECT COUNT(*)
FROM schemeperf;
"""

pd.read_sql(query,conn)

   COUNT(*)
0        40

In [14]:
query = """
SELECT COUNT(*)
FROM transactions;
"""

pd.read_sql(query,conn)

   COUNT(*)
0     32778

In [15]:
query = """
SELECT COUNT(*)
FROM pholdings;
"""

pd.read_sql(query,conn)

   COUNT(*)
0       322

In [16]:
query = """
SELECT COUNT(*)
FROM benchmarks;
"""

pd.read_sql(query,conn)

   COUNT(*)
0      8050