In [ ]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("../data/db/mutualfund.db")

In [2]:
query = """
SELECT COUNT(*)
FROM customers;
"""
pd.read_sql(query,conn)

   COUNT(*)
0        40

In [3]:
query = """
SELECT COUNT(*)
FROM navhistory;
"""

pd.read_sql(query,conn)

   COUNT(*)
0     46000

In [4]:
query = """
SELECT COUNT(*)
FROM aumbyfh;
"""

pd.read_sql(query,conn)

   COUNT(*)
0        90

In [5]:
query = """
SELECT COUNT(*)
FROM sipinflow;
"""

pd.read_sql(query,conn)

   COUNT(*)
0        48

In [6]:
query = """
SELECT COUNT(*)
FROM catinflow;
"""

pd.read_sql(query,conn)

   COUNT(*)
0       144

In [7]:
query = """
SELECT COUNT(*)
FROM foliocount;
"""

pd.read_sql(query,conn)

   COUNT(*)
0        21

In [8]:
query = """
SELECT COUNT(*)
FROM schemeperf;
"""

pd.read_sql(query,conn)

   COUNT(*)
0        40

In [9]:
query = """
SELECT COUNT(*)
FROM transactions;
"""

pd.read_sql(query,conn)

   COUNT(*)
0     32778

In [10]:
query = """
SELECT COUNT(*)
FROM pholdings;
"""

pd.read_sql(query,conn)

   COUNT(*)
0       322

In [11]:
query = """
SELECT COUNT(*)
FROM benchmarks;
"""

pd.read_sql(query,conn)

   COUNT(*)
0      8050